### ISSUE TITLE
API Compliance || Discrepancies Between Application API Spec and POJOs

### ISSUE THREAD

**Issue by varunreddy-egov** [pucardotorg/dristi#726]
**Description:**
All the create, update, and search APIs of the Application return an application object. However, there are discrepancies between the API specifications and the actual `Application` POJO.

**Details:**

**Discrepancy in `issuedBy` field:**
 - According to the API spec, `issuedBy` is defined as:
```
issuedBy:
  type: object
  properties:
    benchID:
      type: string
    judgeID:
      type: array
      items:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
    courtID:
      type: string
```
 - In the Application POJO, it is defined as:
`private Object issuedBy = null;`

**Expected Behavior:**
The application object should match the API specification, with `issuedBy` field correctly defined as per the API spec.

**Actual Behavior:**
 - `issuedBy` is defined as a generic `Object` in the `Application` POJO.

**Additional Information:**
[API Specification](https://github.com/pucardotorg/dristi/blob/develop/api_specifications/application-api-0.1.0.yaml)
