### ISSUE TITLE
API Compliance || Discrepancies Between Hearing API Spec and POJOs

### ISSUE THREAD

**Issue by varunreddy-egov** [pucardotorg/dristi#732]
**Description:**
All the create, update, and search APIs of the Hearing return a `hearing` object. However, there are discrepancies between the API specifications and the actual `Hearing` POJO.

**Details:**

**Discrepancy in `startTime` field:**
 - According to the API spec, `startTime` is defined as:
```
startTime:
  type: string
  format: date
  nullable: true
  description: This field holds information about start date time of hearing in epoch time.
```
 - In the `Hearing` POJO, it is defined as:
```
@JsonProperty("startTime")
@Valid
private Long startTime = null;
```
**Discrepancy in `endTime` field:**
 - According to the API spec, `endTime` is defined as:
```
endTime:
  type: string
  format: date
  nullable: true
  description: This field holds information about end date time of hearing in epoch time. Optional field.
```
 - In the `Hearing` POJO, it is defined as:
```
@JsonProperty("endTime")
@Valid
private Long endTime = null;
```

**Expected Behavior:**
The `hearing` object should match the API specification, with `startTime` and `endTime` fields correctly defined as per the API spec.

**Actual Behavior:**
 - `startTime` and `endTime` fields are defined as `Long` in the `Hearing` POJO but they are defined are `String` as per API spec.

**Additional Information:**
[API Specification](https://github.com/pucardotorg/dristi/blob/develop/api_specifications/hearing-api-0.1.0.yaml)
