### ISSUE TITLE
API Compliance || Discrepancies Between Oder API Spec and POJOs

### ISSUE THREAD

**Issue by varunreddy-egov** [pucardotorg/dristi#733]
**Description:**
There are discrepancies observed between Order APIs and its documented specification.

**Details:**

**Order POJO:**
 - `linkedOrderNumber` field present in POJO but not documented in the API spec
 - Discrepancy in `issuedBy` field:
   -  In the Order POJO, it is defined as:
`private Object issuedBy = null;`
   - According to the API spec, `issuedBy` is defined as:
```
issuedBy:
  type: object
  properties:
    benchID:
      type: string
    judgeID:
      type: array
      items:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
    courtID:
      type: string
```

**OrderExists POJO:**
 - `orderId` field present in POJO but not documented in the API spec.

**Expected Behavior:**
The Order service API responses should accurately reflect the fields and data types as specified in the API documentation.

**Actual Behavior:**
- Order POJO:
  - `linkedOrderNumber` field is present in the response but not documented in the API spec.
  - Discrepancy in the issuedBy field definition between the POJO and the API spec.
- Order Exists POJO:
  - `orderId` field is present in the response but not documented in the API spec.
 
**Proposed Solution:**
1. Update the Order service API specification to include all fields consistently returned in the API responses (linkedOrderNumber and orderId).
2. Ensure the `issuedBy` field in the Order POJO matches the structure defined in the API spec.

**Additional Information:**
[API Specification
](https://github.com/pucardotorg/dristi/blob/main/api_specifications/order-api-0.1.0.yaml)
