### ISSUE TITLE
API Compliance || Discrepancies Between Task API Spec and POJOs

### ISSUE THREAD

**Issue by varunreddy-egov** [pucardotorg/dristi#747]
**Description:**
There are discrepancies observed between Task APIs and its documented specification.

**Details:**

**Task POJO:**
 - `taskNumber` field present in POJO but not documented in the API spec
 - Discrepancy in `assignedTo` field:
   -  In the Task POJO, it is defined as:
`private Object assignedTo = null;`
   - According to the API spec, `assignedTo` is defined as:
```
assignedTo:
  type: object
  description: details of person this task is assigned to. For example in case of document upload, this could be litigant or lawyer. in case of summon task, this will be person to whom summon is issued
  properties:
    individualId:
      type: string
      format: uuid
      minLength: 36
      maxLength: 36
      description: ID of the person if the person is in the system, in which case the name field can be left blank
    name:
      type: string
      description: name of the person if not in the system
```

**Expected Behavior:**
The Task service API responses should accurately reflect the fields and data types as specified in the API documentation.

**Actual Behavior:**
- Task POJO:
  - `taskNumber` field is present in the response but not documented in the API spec.
  - Discrepancy in the `assignedTo` field definition between the POJO and the API spec.
 
**Proposed Solution:**
1. Update the Task service API specification to include all fields consistently returned in the API responses (taskNumber).
2. Ensure the `assignedTo` field in the `Task` POJO matches the structure defined in the API spec.

**Additional Information:**
[API Specification
](https://github.com/pucardotorg/dristi/blob/develop/api_specifications/task-api-0.1.0.yaml)
